import { PolarPlot } from "./PolarPlot";
import { Card } from "./Card";
import { Errors } from "./Errors";
import { sensorName } from "../utils/display";
import { format } from "../utils/display";
import type { Point } from "../calculations/geometry";
import type { TrimBalanceCalculation, PlotPointLabel } from "../types/trimBalance";
import type { Analysis, ResultantMetrics, ResultantSelection, UpdateCalculation } from "./plotTypes";

export function PlotAnalysis({ calculation, update, errors, analyses, active, selected, onSelect, selectedResultants, onSelectResultant, getMetrics }: { calculation: TrimBalanceCalculation; update: UpdateCalculation; errors: string[]; analyses: Analysis[]; active: Analysis | undefined; selected: PlotPointLabel; onSelect: (label: PlotPointLabel) => void; selectedResultants: ResultantSelection; onSelectResultant: (point: Point) => void; getMetrics: (point: Analysis["point"]) => ResultantMetrics | undefined }) {
  const metrics = active ? getMetrics(active.point) : undefined;
  return <Card title="3-shot plot analysis" step={6}><p>Confirm the three central screw positions against approved maintenance data. The defaults reproduce the training example only.</p><div className="position-inputs">{(["first", "second", "third"] as const).map((key) => <label key={key}>{key} central screw position<input type="number" min="1" max="36" value={calculation.testScrewPositions[key]} onChange={(event) => update((item) => ({ ...item, testScrewPositions: { ...item.testScrewPositions, [key]: Number(event.target.value) } }))} /></label>)}</div>{errors.length ? <Errors errors={errors} /> : <><div className="point-tabs">{analyses.map(({ point }) => <button className={point.label === selected ? "active" : ""} key={point.label} onClick={() => onSelect(point.label)}>{point.label}</button>)}</div>{active && <div className="analysis-grid"><div><p className="plot-instruction">Select the center of the common area of the three circles.</p><PolarPlot initialCircle={active.geometry.initialCircle} runCircles={[{ circle: active.geometry.firstCircle, label: "First", color: "#0d7a69" }, { circle: active.geometry.secondCircle, label: "Second", color: "#b76e15" }, { circle: active.geometry.thirdCircle, label: "Third", color: "#7054b8" }]} resultant={selectedResultants[active.point.label]} resultantAngleDeg={metrics?.resultantAngleDeg} onSelectResultant={onSelectResultant} /></div><div className="resultant-details"><h3>Point {active.point.label} · {sensorName(active.point.sensor)}</h3><dl><dt>U0 / initial</dt><dd>{format(active.point.initialVibration)} mils</dd><dt>First / second / third</dt><dd>{format(active.point.firstVibration)} / {format(active.point.secondVibration)} / {format(active.point.thirdVibration)} mils</dd><dt>Resultant R1</dt><dd>{metrics ? `${format(metrics.resultantAmplitude)} mils` : "Select resultant"}</dd><dt>Resultant angle</dt><dd>{metrics ? `${format(metrics.resultantAngleDeg)}°` : "Select resultant"}</dd><dt>W6</dt><dd>{metrics ? `${format(metrics.w6CmG, 0)} cm·g` : "Select resultant"}</dd><dt>Sensitivity</dt><dd>{metrics ? format(metrics.sensitivity, 0) : "Select resultant"}</dd></dl></div></div>}</>}</Card>;
}
