import { useEffect, useMemo, useState } from "react";
import "./App.css";
import { buildPlotPoints } from "./features/trim-balance/calculations/buildPlotPoints";
import { calculatePairwiseAnalysis } from "./features/trim-balance/calculations/pairwiseAnalysis";
import { calculateThreeShotGeometry, polarToCartesian } from "./features/trim-balance/calculations/geometry";
import { RunInputTable } from "./features/trim-balance/components/RunInputTable";
import { PolarPlot } from "./features/trim-balance/components/PolarPlot";
import { validateThreeShotInput } from "./features/trim-balance/utils/validation";
import { N1_SPEEDS, type EngineRun, type N1Speed, type PlotPointLabel, type TrimBalanceCalculation } from "./features/trim-balance/types/trimBalance";

const storageKey = "cfm56-7b-trim-balance-calculations";
const steps = ["Information", "Initial run", "First run", "Second run", "Third run", "Point selection", "3-shot plot", "Final correction", "Final run", "Report"];
const blankRun = (): EngineRun => ({ measurements: N1_SPEEDS.map((n1Speed) => ({ n1Speed, bearingVibration: Number.NaN, ffccvVibration: Number.NaN })) });
const format = (value: number, digits = 1) => Number.isFinite(value) ? value.toFixed(digits) : "—";
const sensorName = (sensor: "bearing" | "ffccv") => sensor === "bearing" ? "N°1 Bearing" : "FFCCV";

function createCalculation(): TrimBalanceCalculation {
  const now = new Date();
  return { information: { id: `TB-${now.toISOString().slice(0, 10).replaceAll("-", "")}`, aircraftRegistration: "", engineSerialNumber: "", engineModel: "CFM56-7B", date: now.toISOString().slice(0, 10), technician: "", notes: "" }, initialRun: blankRun(), firstRun: blankRun(), secondRun: blankRun(), thirdRun: blankRun(), finalRun: blankRun(), limits: {}, testScrewPositions: { first: 35, second: 23, third: 11 }, status: "Draft", updatedAt: now.toISOString() };
}
function restore(item: TrimBalanceCalculation): TrimBalanceCalculation {
  const normalize = (run?: EngineRun): EngineRun => ({ measurements: N1_SPEEDS.map((n1Speed) => { const source = run?.measurements.find((measurement) => measurement.n1Speed === n1Speed); return { n1Speed, bearingVibration: typeof source?.bearingVibration === "number" ? source.bearingVibration : Number.NaN, ffccvVibration: typeof source?.ffccvVibration === "number" ? source.ffccvVibration : Number.NaN }; }) });
  return { ...createCalculation(), ...item, initialRun: normalize(item.initialRun), firstRun: normalize(item.firstRun), secondRun: normalize(item.secondRun), thirdRun: normalize(item.thirdRun), finalRun: normalize(item.finalRun) };
}

function App() {
  const [saved, setSaved] = useState<TrimBalanceCalculation[]>(() => { try { return (JSON.parse(localStorage.getItem(storageKey) ?? "[]") as TrimBalanceCalculation[]).map(restore); } catch { return []; } });
  const [calculation, setCalculation] = useState<TrimBalanceCalculation | null>(null);
  const [step, setStep] = useState(0);
  const [selected, setSelected] = useState<PlotPointLabel>("A");
  useEffect(() => { localStorage.setItem(storageKey, JSON.stringify(saved)); }, [saved]);
  const errors = useMemo(() => calculation ? validateThreeShotInput(calculation) : [], [calculation]);
  const points = useMemo(() => calculation && !errors.length ? buildPlotPoints(calculation.initialRun, calculation.firstRun, calculation.secondRun, calculation.thirdRun) : [], [calculation, errors]);
  const analyses = useMemo(() => calculation ? points.map((point) => ({ point, geometry: calculateThreeShotGeometry({ initialVibration: point.initialVibration, firstRunVibration: point.firstVibration, secondRunVibration: point.secondVibration, thirdRunVibration: point.thirdVibration, firstTestScrewPosition: calculation.testScrewPositions.first, secondTestScrewPosition: calculation.testScrewPositions.second, thirdTestScrewPosition: calculation.testScrewPositions.third }) })) : [], [calculation, points]);
  const active = analyses.find((item) => item.point.label === selected) ?? analyses[0];
  const pairs = useMemo(() => calculatePairwiseAnalysis(analyses.map(({ point, geometry }) => ({ label: point.label, point: polarToCartesian(geometry.w6CmG, geometry.resultantAngleDeg), sensitivity: geometry.sensitivity }))), [analyses]);
  const update = (change: (item: TrimBalanceCalculation) => TrimBalanceCalculation) => setCalculation((item) => item ? { ...change(item), updatedAt: new Date().toISOString(), status: item.status === "Draft" ? "In Progress" : item.status } : item);
  const updateMeasurement = (run: "initialRun" | "firstRun" | "secondRun" | "thirdRun" | "finalRun", speed: N1Speed, field: "bearingVibration" | "ffccvVibration", value: number) => update((item) => ({ ...item, [run]: { measurements: item[run].measurements.map((measurement) => measurement.n1Speed === speed ? { ...measurement, [field]: value } : measurement) } }));
  const save = () => calculation && setSaved((items) => [calculation, ...items.filter((item) => item.information.id !== calculation.information.id)]);
  const start = (item = createCalculation()) => { setCalculation(item); setStep(0); };

  if (!calculation) return <Dashboard saved={saved} onStart={start} />;
  const runPage = (title: string, run: "initialRun" | "firstRun" | "secondRun" | "thirdRun", note: string) => <Card title={title} step={step}><p>{note}</p><RunInputTable run={calculation[run]} onChange={(speed, field, value) => updateMeasurement(run, speed, field, value)} /><p className="field-note">Enter measured vibration amplitudes in mils. The application does not transform or round your entries.</p></Card>;
  let page: React.ReactNode;
  if (step === 0) page = <Information calculation={calculation} update={update} />;
  else if (step === 1) page = runPage("Initial run", "initialRun", "Record both sensor outputs at each specified N1 target.");
  else if (step === 2) page = runPage("First run", "firstRun", "Record the run with the procedure’s first test-weight configuration installed.");
  else if (step === 3) page = runPage("Second run", "secondRun", "Record the run after repositioning test weights per approved maintenance data.");
  else if (step === 4) page = runPage("Third run", "thirdRun", "Record the third test-weight configuration at the same N1 targets.");
  else if (step === 5) page = <Card title="Automatic plot-point selection" step={step}><p>The three highest Initial Run amplitudes for each sensor are selected as A–F.</p>{errors.length ? <Errors errors={errors} /> : <PointTable points={points} />}</Card>;
  else if (step === 6) page = <PlotAnalysis calculation={calculation} update={update} errors={errors} analyses={analyses} active={active} selected={selected} onSelect={setSelected} />;
  else if (step === 7) page = <Correction errors={errors} points={points} analyses={analyses} pairs={pairs} />;
  else if (step === 8) page = <FinalRun calculation={calculation} update={update} updateMeasurement={updateMeasurement} />;
  else page = <Report calculation={calculation} points={points} />;
  return <main className="workspace"><header className="app-header compact"><button className="brand" onClick={() => { save(); setCalculation(null); }}>FAN TRIM BALANCE <span>CFM56-7B · 3-SHOT PLOT</span></button><div><span className="badge">{calculation.status}</span><button className="secondary" onClick={save}>Save locally</button></div></header><nav className="stepper">{steps.map((name, index) => <button key={name} className={index === step ? "current" : index < step ? "done" : ""} onClick={() => setStep(index)}><span>{index + 1}</span>{name}</button>)}</nav>{page}<footer className="wizard-actions"><button className="secondary" disabled={!step} onClick={() => setStep(step - 1)}>Back</button><span>{errors.length && step >= 5 ? "Complete all four runs before analysis." : "Save to retain this calculation in this browser."}</span><button className="primary" onClick={() => { save(); setStep(Math.min(steps.length - 1, step + 1)); }}>{step === steps.length - 1 ? "Save calculation" : "Save & continue"}</button></footer></main>;
}

function Dashboard({ saved, onStart }: { saved: TrimBalanceCalculation[]; onStart: (item?: TrimBalanceCalculation) => void }) { return <main className="dashboard"><header className="app-header"><div><span className="eyebrow">ENGINEERING DECISION SUPPORT</span><h1>Fan Trim Balance</h1><p>CFM56-7B · 3-Shot Plot</p></div><button className="primary" onClick={() => onStart()}>+ New calculation</button></header><div className="safety-note"><strong>Maintenance-data warning.</strong> This is a calculation/decision-support tool. Confirm current approved AMM data before operational use.</div><section className="dashboard-grid"><article className="stat-card"><span>Saved calculations</span><strong>{saved.length}</strong></article><article className="stat-card"><span>Completed</span><strong>{saved.filter((item) => item.status === "Completed").length}</strong></article><article className="stat-card"><span>Draft / in progress</span><strong>{saved.filter((item) => item.status !== "Completed").length}</strong></article></section><section className="card"><h2>Recent calculations</h2>{saved.length ? <div className="table-wrap"><table><thead><tr><th>Reference</th><th>Aircraft</th><th>Engine S/N</th><th>Status</th><th></th></tr></thead><tbody>{saved.map((item) => <tr key={item.information.id}><td>{item.information.id}</td><td>{item.information.aircraftRegistration || "—"}</td><td>{item.information.engineSerialNumber || "—"}</td><td><span className="badge">{item.status}</span></td><td><button className="link-button" onClick={() => onStart(item)}>Open</button></td></tr>)}</tbody></table></div> : <p className="muted">No saved calculations yet.</p>}</section></main> }
function Card({ title, step, children }: { title: string; step: number; children: React.ReactNode }) { return <section className="card"><span className="eyebrow">STEP {step + 1}</span><h2>{title}</h2>{children}</section> }
function Information({ calculation, update }: { calculation: TrimBalanceCalculation; update: (change: (item: TrimBalanceCalculation) => TrimBalanceCalculation) => void }) { const fields = [['id','Calculation ID / reference'],['aircraftRegistration','Aircraft registration'],['engineSerialNumber','Engine serial number'],['engineModel','Engine model'],['date','Date'],['technician','Technician / engineer']] as const; return <Card title="Calculation information" step={0}><p>Reference fields identify this local calculation record. They are not mandatory calculation inputs.</p><div className="form-grid">{fields.map(([key,label]) => <label key={key}>{label}<input type={key === "date" ? "date" : "text"} value={calculation.information[key]} onChange={(event) => update((item) => ({ ...item, information: { ...item.information, [key]: event.target.value } }))} /></label>)}<label className="full-width">Notes<textarea value={calculation.information.notes} onChange={(event) => update((item) => ({ ...item, information: { ...item.information, notes: event.target.value } }))} /></label></div></Card> }
function Errors({ errors }: { errors: string[] }) { return <div className="validation"><strong>Analysis unavailable</strong><ul>{errors.map((error) => <li key={error}>{error}</li>)}</ul></div> }
function PointTable({ points, analyses }: { points: ReturnType<typeof buildPlotPoints>; analyses?: { point: ReturnType<typeof buildPlotPoints>[number]; geometry: ReturnType<typeof calculateThreeShotGeometry> }[] }) { return <div className="table-wrap"><table><thead><tr><th>Point</th><th>Sensor</th><th>N1</th><th>Initial</th><th>First</th><th>Second</th><th>Third</th>{analyses && <><th>R1</th><th>Angle</th><th>W6</th><th>Sensitivity</th></>}</tr></thead><tbody>{points.map((point) => { const geometry = analyses?.find((item) => item.point.label === point.label)?.geometry; return <tr key={point.label}><td><strong>{point.label}</strong></td><td>{sensorName(point.sensor)}</td><td>{point.n1Speed}</td><td>{format(point.initialVibration)}</td><td>{format(point.firstVibration)}</td><td>{format(point.secondVibration)}</td><td>{format(point.thirdVibration)}</td>{geometry && <><td>{format(geometry.resultantAmplitude)}</td><td>{format(geometry.resultantAngleDeg)}°</td><td>{format(geometry.w6CmG, 0)}</td><td>{format(geometry.sensitivity, 0)}</td></>}</tr> })}</tbody></table></div> }
function PlotAnalysis({ calculation, update, errors, analyses, active, selected, onSelect }: { calculation: TrimBalanceCalculation; update: (change: (item: TrimBalanceCalculation) => TrimBalanceCalculation) => void; errors: string[]; analyses: { point: ReturnType<typeof buildPlotPoints>[number]; geometry: ReturnType<typeof calculateThreeShotGeometry> }[]; active: { point: ReturnType<typeof buildPlotPoints>[number]; geometry: ReturnType<typeof calculateThreeShotGeometry> } | undefined; selected: PlotPointLabel; onSelect: (label: PlotPointLabel) => void }) { return <Card title="3-shot plot analysis" step={6}><p>Confirm the three central screw positions against approved maintenance data. The defaults reproduce the training example only.</p><div className="position-inputs">{(['first','second','third'] as const).map((key) => <label key={key}>{key} central screw position<input type="number" min="1" max="36" value={calculation.testScrewPositions[key]} onChange={(event) => update((item) => ({ ...item, testScrewPositions: { ...item.testScrewPositions, [key]: Number(event.target.value) } }))} /></label>)}</div>{errors.length ? <Errors errors={errors} /> : <><div className="point-tabs">{analyses.map(({ point }) => <button className={point.label === selected ? "active" : ""} key={point.label} onClick={() => onSelect(point.label)}>{point.label}</button>)}</div>{active && <div className="analysis-grid"><PolarPlot initialCircle={active.geometry.initialCircle} runCircles={[{ circle: active.geometry.firstCircle, label: "First", color: "#0d7a69" },{ circle: active.geometry.secondCircle, label: "Second", color: "#b76e15" },{ circle: active.geometry.thirdCircle, label: "Third", color: "#7054b8" }]} resultant={active.geometry.resultantPoint} resultantAngleDeg={active.geometry.resultantAngleDeg} /><div className="resultant-details"><h3>Point {active.point.label} · {sensorName(active.point.sensor)}</h3><dl><dt>U0 / initial</dt><dd>{format(active.point.initialVibration)} mils</dd><dt>First / second / third</dt><dd>{format(active.point.firstVibration)} / {format(active.point.secondVibration)} / {format(active.point.thirdVibration)} mils</dd><dt>Resultant R1</dt><dd>{format(active.geometry.resultantAmplitude)} mils</dd><dt>Resultant angle</dt><dd>{format(active.geometry.resultantAngleDeg)}°</dd><dt>W6</dt><dd>{format(active.geometry.w6CmG, 0)} cm·g</dd><dt>Sensitivity</dt><dd>{format(active.geometry.sensitivity, 0)}</dd></dl></div></div>}</>}</Card> }
function Correction({ errors, points, analyses, pairs }: { errors: string[]; points: ReturnType<typeof buildPlotPoints>; analyses: { point: ReturnType<typeof buildPlotPoints>[number]; geometry: ReturnType<typeof calculateThreeShotGeometry> }[]; pairs: ReturnType<typeof calculatePairwiseAnalysis> }) { return <Card title="Final correction review" step={7}><p>A–F weight points and the manual worksheet pair quantity U are shown for inspection.</p>{errors.length ? <Errors errors={errors} /> : <><PointTable points={points} analyses={analyses} /><h3>Pairwise analysis</h3><div className="table-wrap"><table><thead><tr><th>Pair</th><th>Distance (cm·g)</th><th>Combined sensitivity</th><th>U</th></tr></thead><tbody>{pairs.map((pair) => <tr key={pair.pair}><td>{pair.pair}</td><td>{format(pair.distanceCmG, 0)}</td><td>{format(pair.combinedSensitivity, 0)}</td><td>{format(pair.amplitude, 3)}</td></tr>)}</tbody></table></div><div className="todo-card"><strong>PO weight mapping not configured.</strong><p>The final-vector selection and physical PO screw chart require verified worksheet/AMM data. No final correction or screw combination is fabricated.</p></div></>}</Card> }
function FinalRun({ calculation, update, updateMeasurement }: { calculation: TrimBalanceCalculation; update: (change: (item: TrimBalanceCalculation) => TrimBalanceCalculation) => void; updateMeasurement: (run: "finalRun", speed: N1Speed, field: "bearingVibration" | "ffccvVibration", value: number) => void }) { const breaches = calculation.finalRun.measurements.flatMap((m) => [calculation.limits.bearing !== undefined && Number.isFinite(m.bearingVibration) && m.bearingVibration > calculation.limits.bearing ? `${m.n1Speed} bearing exceeds configured limit` : null, calculation.limits.ffccv !== undefined && Number.isFinite(m.ffccvVibration) && m.ffccvVibration > calculation.limits.ffccv ? `${m.n1Speed} FFCCV exceeds configured limit` : null].filter((item): item is string => Boolean(item))); return <Card title="Final run and applicable limits" step={8}><p>Limits are optional configuration values. Enter only limits verified from applicable maintenance data.</p><div className="limits"><label>N°1 bearing limit <small>mils, optional</small><input type="number" min="0" step="0.1" value={calculation.limits.bearing ?? ""} onChange={(event) => update((item) => ({ ...item, limits: { ...item.limits, bearing: event.target.value === "" ? undefined : Number(event.target.value) } }))} /></label><label>FFCCV limit <small>mils, optional</small><input type="number" min="0" step="0.1" value={calculation.limits.ffccv ?? ""} onChange={(event) => update((item) => ({ ...item, limits: { ...item.limits, ffccv: event.target.value === "" ? undefined : Number(event.target.value) } }))} /></label></div><RunInputTable run={calculation.finalRun} comparisonRun={calculation.initialRun} onChange={(speed, field, value) => updateMeasurement("finalRun", speed, field, value)} />{calculation.limits.bearing === undefined && calculation.limits.ffccv === undefined ? <div className="todo-card">Applicable maintenance limits not configured. No pass/fail claim is made.</div> : <div className={breaches.length ? "validation" : "success"}><strong>{breaches.length ? "Configured-limit review required" : "All entered final measurements are within configured limits"}</strong>{breaches.length > 0 && <ul>{breaches.map((item) => <li key={item}>{item}</li>)}</ul>}</div>}</Card> }
function Report({ calculation, points }: { calculation: TrimBalanceCalculation; points: ReturnType<typeof buildPlotPoints> }) { return <Card title="Calculation summary / report" step={9}><dl className="report-list"><dt>Reference</dt><dd>{calculation.information.id}</dd><dt>Aircraft</dt><dd>{calculation.information.aircraftRegistration || "Not recorded"}</dd><dt>Engine</dt><dd>{calculation.information.engineModel} {calculation.information.engineSerialNumber && `· ${calculation.information.engineSerialNumber}`}</dd><dt>Plot points</dt><dd>{points.length === 6 ? "A–F selected" : "Incomplete"}</dd><dt>Final correction</dt><dd>Not calculated — verified final-vector and PO chart data required.</dd></dl><div className="safety-note"><strong>Not an approved maintenance instruction.</strong> Review this record, current AMM data, applicable limits, and the physical weight chart before maintenance action.</div></Card> }

export default App;
